homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.3
  longitude: 14.3
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 260
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

mqtt:
  broker: 192.168.12.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

# Example configuration.yaml entry
media_player:
  - platform: spotify
    client_id: 7afaaa94d0db4dc7ab6fcd5e85dd685d
    client_secret: 65ede2960e484003858fbae23e5ec8ee
    aliases:
        abc123def456: 'Living Room'
        9183abas000: 'Bed Room'

light:
  - platform: mqtt
    name: "LED-Strip"
    command_topic: "ledstrip/ledstrip/set"
    payload_on: "on"
    payload_off: "off"

switch:
  - platform: mqtt
    name: "Door Lock"
    command_topic: "door/lock/set"
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    name: "Cooling"
    command_topic: "bdop/ac/set"
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    name: "Spotify"
    command_topic: "bdop/spotify/set"
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    name: "PartyMode"
    command_topic: "bdop/partymode/set"
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    name: "HipHop"
    command_topic: "bdop/hiphop/set"
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    name: "Romantic"
    command_topic: "bdop/romantic/set"
    payload_on: "on"
    payload_off: "off"

binary_sensor:
  - platform: mqtt
    name: "Motion-Sensor"
    state_topic: "bdop/motion_sensor"
    payload_on: "motion"
    payload_off: "no_motion"
